### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by zaclark369** [zaclark369/Pantry#1]

**Comment by zaclark369** [comment]
- what this would look like
- what the template should be

**Comment by katieclauswell** [comment]
Editable link shared in slack. [View only here.](https://www.canva.com/design/DAE4G0BZFqw/ZoQjKFJhwD0TrbFwF-VHeA/view?utm_content=DAE4G0BZFqw&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton&mode=preview)
